# Generated by Django 2.1.7 on 2019-04-06 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upgrades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='upgrades',
            name='exp_for_update',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
