# Generated by Django 2.1.7 on 2019-04-06 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upgrades', '0002_upgrades_exp_for_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='upgrades',
            name='icon',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
