# Generated by Django 2.1.7 on 2019-04-07 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upgrades', '0004_upgradessets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upgrades',
            name='icon',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.RemoveField(
            model_name='upgradessets',
            name='upd_sets',
        ),
        migrations.AddField(
            model_name='upgradessets',
            name='upd_sets',
            field=models.ManyToManyField(to='upgrades.Upgrades'),
        ),
    ]
