# Generated by Django 2.1.7 on 2019-04-08 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upgrades', '0005_auto_20190407_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upgradessets',
            name='upd_sets',
        ),
        migrations.AddField(
            model_name='upgradessets',
            name='item_1',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='upgrades.Upgrades'),
        ),
        migrations.AddField(
            model_name='upgradessets',
            name='item_2',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='upgrades.Upgrades'),
        ),
        migrations.AddField(
            model_name='upgradessets',
            name='item_3',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='upgrades.Upgrades'),
        ),
        migrations.AddField(
            model_name='upgradessets',
            name='item_4',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='upgrades.Upgrades'),
        ),
    ]
