# Generated by Django 2.1.7 on 2019-04-08 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upgrades', '0006_auto_20190408_0758'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rarity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rarity', models.CharField(max_length=10)),
            ],
        ),
        migrations.RenameField(
            model_name='upgrades',
            old_name='name',
            new_name='Upgrades_name',
        ),
        migrations.AddField(
            model_name='upgrades',
            name='Upgrades_rarity',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='upgrades.Rarity'),
        ),
    ]
