# Generated by Django 2.1.7 on 2019-04-08 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upgrades', '0007_auto_20190408_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='upgrades',
            name='Upgrades_property',
            field=models.CharField(blank=True, default=None, max_length=24, null=True),
        ),
    ]
