# Generated by Django 2.1.7 on 2019-04-08 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upgrades', '0008_upgrades_upgrades_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upgrades',
            name='icon',
            field=models.ImageField(blank=True, upload_to='upgrade_images/'),
        ),
    ]
