# Generated by Django 2.1.7 on 2019-04-09 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upgrades', '0011_auto_20190408_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upgradessets',
            name='name',
            field=models.CharField(max_length=34),
        ),
    ]
