# Generated by Django 2.1.7 on 2019-04-09 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upgrades', '0012_auto_20190409_0757'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='upgradessets',
            options={'verbose_name': 'Upgrade set', 'verbose_name_plural': 'Upgrade sets'},
        ),
        migrations.RenameField(
            model_name='upgrades',
            old_name='exp_for_update',
            new_name='exp_for_upgrade',
        ),
        migrations.RenameField(
            model_name='upgrades',
            old_name='gold_for_update',
            new_name='gold_for_upgrade',
        ),
        migrations.AddField(
            model_name='upgradessets',
            name='Set_exp_for_upgrade',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='upgradessets',
            name='Set_gold_for_sell',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='upgradessets',
            name='Set_gold_for_upgrade',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
