# Generated by Django 2.1.7 on 2019-04-09 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upgrades', '0013_auto_20190409_0858'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upgradessets',
            old_name='Set_gold_for_sell',
            new_name='Set_gold_for_sale',
        ),
    ]
