# Generated by Django 2.1.7 on 2019-04-09 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upgrades', '0014_auto_20190409_0907'),
    ]

    operations = [
        migrations.CreateModel(
            name='Heroes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heroes_name', models.CharField(max_length=24)),
            ],
        ),
        migrations.RenameField(
            model_name='upgrades',
            old_name='Upgrades_name',
            new_name='upgrades_name',
        ),
        migrations.RenameField(
            model_name='upgrades',
            old_name='Upgrades_rarity',
            new_name='upgrades_rarity',
        ),
        migrations.RenameField(
            model_name='upgradessets',
            old_name='Set_exp_for_upgrade',
            new_name='set_exp_for_upgrade',
        ),
        migrations.RenameField(
            model_name='upgradessets',
            old_name='Set_gold_for_sale',
            new_name='set_gold_for_sale',
        ),
        migrations.RenameField(
            model_name='upgradessets',
            old_name='Set_gold_for_upgrade',
            new_name='set_gold_for_upgrade',
        ),
        migrations.AddField(
            model_name='heroes',
            name='heroes_sets',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upgrades.UpgradesSets'),
        ),
    ]
