# Generated by Django 2.1.7 on 2019-04-09 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upgrades', '0015_auto_20190409_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroes',
            name='heroes_sets3',
            field=models.ManyToManyField(related_name='heroess', to='upgrades.UpgradesSets'),
        ),
    ]
