# Generated by Django 2.1.7 on 2019-04-10 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upgrades', '0021_auto_20190410_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RenameField(
            model_name='upgrades',
            old_name='Upgrades_property',
            new_name='upgrades_property',
        ),
        migrations.RemoveField(
            model_name='heroes',
            name='heroes_sets',
        ),
        migrations.AddField(
            model_name='upgradessets',
            name='heroes',
            field=models.ManyToManyField(related_name='UpgradesSets', to='upgrades.Heroes'),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
