# Generated by Django 2.1.7 on 2019-04-22 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upgrades', '0022_auto_20190410_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lvl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('lvl_sets', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='upgrades.UpgradesSets')),
            ],
        ),
        migrations.AddField(
            model_name='heroes',
            name='exp',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
