# Generated by Django 2.1.7 on 2019-04-23 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upgrades', '0023_auto_20190422_0807'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setsinlvl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='lvl',
            name='lvl_sets',
        ),
        migrations.AddField(
            model_name='setsinlvl',
            name='lvl',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='upgrades.Lvl'),
        ),
        migrations.AddField(
            model_name='setsinlvl',
            name='upgradesSets',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='upgrades.UpgradesSets'),
        ),
    ]
